### ISSUE TITLE
Error when depending on other module

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-log-export#10]
When we depend on another module for the `project`, `folder`, or `org_id` fields, we get a "count cannot be computed" error on the log sink module.

**Background**
* [Terraform bug](https://github.com/hashicorp/terraform/issues/12570)
* [HCL Bug](https://github.com/hashicorp/terraform/issues/18015)

**Comment by aaron-lane** [comment]
Fixed by #15.
