### ISSUE TITLE
partition_expiration_days does not apply to partitions already created

### ISSUE THREAD

**Issue by sez76** [terraform-google-modules/terraform-google-log-export#184]
### TL;DR

partition_expiration_days does not apply to partitions already created, after my modification the partion stay on "Partitions do not expire", but if a new partition was created, I have my Partition expiration with the value I have set.

### Terraform Configuration

```hcl
module "log_export_to_biqquery" {
  source                 = "terraform-google-modules/log-export/google"
  version                = "~> 7.6.0"
  destination_uri        = "bigquery.googleapis.com/projects/${var.project_id}/datasets/logs_${var.environment}"
  filter                 = local.bq_logs_filter
  log_sink_name          = "sk-ccoe-logging-bq-${var.environment}"
  parent_resource_id     = var.organization_id
  parent_resource_type   = "organization"
  include_children       = true
  unique_writer_identity = true
  bigquery_options = {
    use_partitioned_tables = true
  }
}

module "bigquery_destination" {
  source                     = "terraform-google-modules/log-export/google//modules/bigquery"
  version                    = "~> 7.6.0"
  project_id                 = var.project_id
  dataset_name               = "logs_${var.environment}"
  location                   = var.default_location
  log_sink_writer_identity   = module.log_export_to_biqquery.writer_identity
  expiration_days            = var.audit_logs_table_expiration_days
  partition_expiration_days  = var.partition_expiration_days
  delete_contents_on_destroy = var.audit_logs_table_delete_contents_on_destroy
```

### Terraform Version

```sh
Terraform v1.6.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.84.0
```

**Comment by imrannayer** [comment]
@sez76 this is not an issue with the module . According to [Provider docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset#default_partition_expiration_ms)



"Once this property is set, all newly-created partitioned tables in the dataset will have an expirationMs property in the timePartitioning settings set to this value, **and changing the value will only affect new tables, not existing ones.** "

**Comment by sez76** [comment]
> @sez76 this is not an issue with the module . According to [Provider docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset#default_partition_expiration_ms)
> 
> 
> 
> "Once this property is set, all newly-created partitioned tables in the dataset will have an expirationMs property in the timePartitioning settings set to this value, **and changing the value will only affect new tables, not existing ones.** "
> 

Hi, yes I have seen on the gcp documentation after I have crete this report, I forget to close it.
