### ISSUE TITLE
Missing support for google provider v6

### ISSUE THREAD

**Issue by lra** [terraform-google-modules/terraform-google-log-export#232]
### TL;DR

Using this module prevents us to use https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.2.0

**Comment by lra** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-google-log-export/pull/228

**Comment by d-costa** [comment]
Any ideia when a version with v6 support will be released?

**Comment by lra** [comment]
Reopening the issue as the fix PR has been closed.

**Comment by lra** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-google-log-export/pull/235
