### ISSUE TITLE
Combine parent_resource_id and parent_resource_type into a single param

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-log-export#28]
Similarly to the work done on other modules (ex.https://github.com/terraform-google-modules/terraform-google-folders/issues/6) we should combine the two parent variables into a single parent variable which accepts input as `folders/{id}` or such.

We should keep the example input variables/test fixtures as-is to demonstrate the process of combining them together within the example itself.

**Comment by kopachevsky** [comment]
@averbuks how are you doing with the task? if you didn't started yet, I can take a look

**Comment by averbuks** [comment]
Hi @kopachevsky, I did not start yet, feel free to take it. I did same change for 2 other modules (this one looks a bit more complex), feel free to reach out to me if any questions.

**Comment by morgante** [comment]
I'm closing this because we don't want to make selection dynamic.

**Comment by ivankorn** [comment]
> I'm closing this because we don't want to make selection dynamic.

Is https://github.com/terraform-google-modules/terraform-google-log-export/pull/30 still valid, it's all green and ready to be merged
cc: @kopachevsky
