### ISSUE TITLE
GCS bucket options

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-log-export#4]
We should have an option to change the default 'MULTI_REGIONAL' bucket to other types of GCS buckets, like 'COLDLINE', 'NEARLINE' or 'REGIONAL'.

We should also be able to specify an expiration for objects in the bucket, using 'lifecycle' option for GCS Terraform resource.

**Comment by kiran002** [comment]
@ocervell you can assign this to me, if you like my idea in #14 I can extend these properties as well

**Comment by aaron-lane** [comment]
Storage class request fixed by #16.
