### ISSUE TITLE
Refactor examples for level instead of destination types

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-log-export#5]
Currently, the examples are organized as follow:

* bigquery
* pubsub
* storage

Since someone that wants to setup a logsink usually thinks about project/folder/organization sinks before the destination, we should refactor the examples like so:

* project-level
* folder-level
* org-level

**Comment by morgante** [comment]
This too: https://github.com/terraform-google-modules/terraform-google-log-export/pull/1#discussion_r217513769
