### ISSUE TITLE
Error: google-beta does not support "google_project_service_identity".

### ISSUE THREAD

**Issue by daniel-cit** [terraform-google-modules/terraform-google-log-export#60]
`make docker_test_lint` is failing with:

```
terraform_validate ./test/setup

Error: Invalid resource type

  on .terraform/modules/project/modules/project_services/main.tf line 38, in resource "google_project_service_identity" "project_service_identities":
  38: resource "google_project_service_identity" "project_service_identities" {

The provider provider.google-beta does not support resource type
"google_project_service_identity".

```

It is relate to the [Support service_identity #448](https://github.com/terraform-google-modules/terraform-google-project-factory/issues/448) in the [new release of project-factory](https://github.com/terraform-google-modules/terraform-google-project-factory/releases/tag/v9.1.0)

To fix we cloud  bump the version of the google beta provider
https://github.com/terraform-google-modules/terraform-google-log-export/blob/c131b330ed9fd854ef993245fb150c7368d832ca/test/setup/versions.tf#L26

From:

```
provider "google-beta" {
  version = "~> 3.36.0"
}
```

to 

```
provider "google-beta" {
  version = "~> 3.38.0"
}
```

OR 

add more control over the major version of the project factory module in the test setup and bump the google-beta provider later.

https://github.com/terraform-google-modules/terraform-google-log-export/blob/c131b330ed9fd854ef993245fb150c7368d832ca/test/setup/main.tf#L19

From:

```
module "project" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 9.0"
```

To:

```
module "project" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 9.0.0"
```

**Comment by bharathkkb** [comment]
We should just bump the providers for now. I opened an issue to track as I have been noticing this across modules.
