### ISSUE TITLE
pubsub_subscriber_role applied to subscription (vs topic)

### ISSUE THREAD

**Issue by huron25** [terraform-google-modules/terraform-google-log-export#91]
I believe that this IAM role should be applied to the subscription (instead of the topic).

Here's the resource (currently line 76 of https://github.com/terraform-google-modules/terraform-google-log-export/blob/master/modules/pubsub/main.tf) :

```
resource "google_pubsub_topic_iam_member" "pubsub_subscriber_role" {
  count   = var.create_subscriber ? 1 : 0
  role    = "roles/pubsub.subscriber"
  project = var.project_id
  topic   = local.topic_name
  member  = "serviceAccount:${google_service_account.pubsub_subscriber[0].email}"
}
```

As far as I can have been able to tell with using this and manual testing in the UI, this permission does not get inherited to the from the Pub/Sub topic to the subscription - to get something to pull messages using the destination pub/sub module, I had to manually add the subscriber created by this module to the subscription also created by this module.

I think the correction is just applying that role to the subscription instead of the topic:

```
resource "google_pubsub_subscription_iam_member" "pubsub_subscriber_role" {
  count   = var.create_subscriber ? 1 : 0
  role    = "roles/pubsub.subscriber"
  project = var.project_id
  subscription = google_pubsub_subscription.pubsub_subscription.name
  member  = "serviceAccount:${google_service_account.pubsub_subscriber[0].email}"
}
```

**Comment by huron25** [comment]
Upon further review, I think it actually should be corrected to this:

resource "google_pubsub_topic_iam_member" "pubsub_viewer_role" {
  count         = var.create_subscriber ? 1 : 0
  role          = "roles/pubsub.viewer"
  project       = var.project_id
  subscription  = local.pubsub_subscription
  member        = "serviceAccount:${google_service_account.pubsub_subscriber[0].email}"
}

My apologies for overlooking the local subscription reference.

**Comment by morgante** [comment]
In my testing before, permissions *have* been inherited so I'm unsure why that changed. Are you using a push or pull subscription?

**Comment by huron25** [comment]
I'm using a Pull subscription.

Even when I do it manually in the UI, I do not see that users given the subscriber role to a topic have any permissions on the associated subscription.

**Comment by huron25** [comment]
Here's the output from projects.topics.getIamPolicy:

{
  "version": 1,
  "etag": "BwXBLs1ROoM=",
  "bindings": [
    {
      "role": "roles/pubsub.subscriber",
      "members": [
        "user:kenmoore@umich.edu"
      ]
    }
  ]
}

And the output from the API call of associated subscription (projects.subscriptions.getIamPolicy):

{
  "etag": "ACAB"
}

**Comment by morgante** [comment]
Right, they wouldn't show up on the subscription necessarily.

I'm curious about the actual behavior—are you not able to pull from the subscription?

**Comment by huron25** [comment]
We're pulling it via the Splunk Add-on for GCP - I've published multiple test messages and Splunk is NOT able to pull them when a service account has Subscriber on the Topic

The moment that I give the service account the Subscriber role on the Subscription, Splunk can then pull them (immediately).

**Comment by morgante** [comment]
Odd, do you mind opening a pull request to fix it?

**Comment by huron25** [comment]
I actually have the code fixed locally, but don't know how to do the testing

**Comment by morgante** [comment]
@huron25 If you open a pull request, our CI will run the tests.

You can also learn more in our codelab: https://codelabs.developers.google.com/codelabs/cft-onboarding/#0
